# Generated by Django 5.1.7 on 2025-03-11 11:37

import mdeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0002_post_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=mdeditor.fields.MDTextField(blank=True, null=True),
        ),
    ]
